# Generated by Django 4.2.7 on 2023-11-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
