# Generated by Django 4.2.7 on 2023-11-04 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0004_order_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='operator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oper', to='tg.telegramuser'),
        ),
    ]
