# Generated by Django 4.2.7 on 2023-11-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0007_alter_telegramuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('kgs_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crypto', models.CharField(max_length=25)),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
