# Generated by Django 4.2.7 on 2023-11-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0008_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentUsdtCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdt', models.FloatField()),
            ],
        ),
    ]
