# Generated by Django 4.2.7 on 2023-11-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0010_exchange_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='crypto',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='kgs_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
