# Generated by Django 4.2.7 on 2023-11-05 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0011_alter_exchange_amount_alter_exchange_crypto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='id',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='user',
        ),
        migrations.AddField(
            model_name='exchange',
            name='order_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tg.order'),
            preserve_default=False,
        ),
    ]
