# Generated by Django 4.2.7 on 2023-11-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0013_chat_tgmessage_remove_exchange_order_ptr_exchange_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgmessage',
            name='message_id',
            field=models.IntegerField(),
        ),
    ]
