# Generated by Django 4.2.7 on 2023-11-05 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0014_alter_tgmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user', to='tg.telegramuser'),
        ),
        migrations.AlterField(
            model_name='tgmessage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='tg.chat'),
        ),
    ]
