# Generated by Django 4.2.7 on 2023-11-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0015_alter_chat_user_alter_tgmessage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgmessage',
            name='message_id',
            field=models.IntegerField(unique=True),
        ),
    ]
