# Generated by Django 4.2.7 on 2023-11-07 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0016_alter_tgmessage_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg.telegramuser'),
        ),
    ]
