# Generated by Django 4.2.7 on 2023-11-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0017_exchange_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentusdtcourse',
            name='coms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchange',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator', to='tg.telegramuser'),
        ),
    ]
