# Generated by Django 4.2.7 on 2023-11-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0019_alter_tgmessage_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tgmessage',
            options={'ordering': ['-last_activity']},
        ),
        migrations.AddField(
            model_name='tgmessage',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
