# Generated by Django 4.2.7 on 2023-11-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0020_alter_tgmessage_options_tgmessage_last_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ['-last_activity']},
        ),
        migrations.AlterModelOptions(
            name='tgmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='tgmessage',
            name='last_activity',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
