# Generated by Django 4.2.7 on 2023-11-07 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0023_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg.telegramuser'),
        ),
    ]
