# Generated by Django 4.2.7 on 2023-11-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0026_payment_coms_payment_usdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='coms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='usdt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
