# Generated by Django 4.2.7 on 2023-11-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0031_exchange_balance_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_text', models.CharField(max_length=5, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
